language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
services:
  - mysql
before_script: 
  - phpenv config-add test/_files/travis.php.ini
  - composer install --dev
  - mysql -u root -e 'create database autowp_test;'
  - mysql -u root < test/_files/dump.sql
