language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
services:
  - mysql
install:
  - printf "\n" | pecl install imagick
  - printf "\n" | pecl install memcache
  - printf "\n" | pecl install geos
before_script: 
  - composer install --dev
  - mysql -u root -e 'create database autowp_test;'
  - mysql -u root < test/_files/dump.sql
