sudo: required
dist: trusty
language: php
php:
  - '7.0'
git:
  submodules: false
services:
  - mysql
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
install:
  - sudo apt-get install php7.0-dev -y
  - printf "\n" | pecl install imagick
  - printf "\n" | pecl install memcache
before_script: 
  - phpenv config-add module/Application/test/ApplicationTest/_files/travis.php.ini
  - composer install --ignore-platform-reqs
  - mysql -u root -e 'create database autowp_test;'
  - mysql -u root < module/Application/test/ApplicationTest/_files/dump.sql
script: ./vendor/bin/phpunit module/Application/test/
